<html>
    <head>
        <title>Whatever</title>
        <style>
            .header {
                background-color: darkblue;
                display: flex;
                justify-content: center;
                color: yellow;
                font-family: Helvetica, serif;
                font-size: 2em;
                font-weight: bold;
                align-content: center;
            }
        </style>
    </head>

    <body>
        <div class="header">Test DAM client</div>
    </body>
</html>