server:
  port: 8080

spring:
  application:
    name: dam-domain-graph
  threads:
    virtual:
      enabled: true

management:
  health:
    cassandra:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

eureka.instance:
  hostname: localhost

graph:
  backend: berkeley

gg:
  jte:
    development-mode: true
    template-location: src/main/resources/templates/